- model_name: deepseek-r1-distill-qwen-32b-quantized
  litellm_params:
    model: hosted_vllm//mnt/wangxiaolei/model/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B-quantized.w8a8
    api_key: EMPTY
    api_base: http://localhost:8000/v1
    max_parallel_requests: 60
    max_retries: 3
    timeout: 60