- model_name: qwen2.5-32b-instruct-gptq-int8
  litellm_params:
    model: hosted_vllm//mnt/wangxiaolei/model/Qwen/Qwen2.5-32B-Instruct-GPTQ-Int8
    api_key: EMPTY
    api_base: http://localhost:8006/v1
    max_parallel_requests: 40
    max_retries: 3
    timeout: 60
- model_name: qwen2.5-32b-instruct-gptq-int8
  litellm_params:
    model: hosted_vllm//mnt/wangxiaolei/model/Qwen/Qwen2.5-32B-Instruct-GPTQ-Int8
    api_key: EMPTY
    api_base: http://localhost:8007/v1
    max_parallel_requests: 40
    max_retries: 3
    timeout: 60