- model_name: qwen
  litellm_params:
    model: hosted_vllm//media/public/models/huggingface/Qwen/Qwen2.5-7B-Instruct
    api_key: EMPTY
    api_base: http://localhost:8000/v1
    max_parallel_requests: 120
    max_retries: 3
    timeout: 60
- model_name: qwen
  litellm_params:
    model: hosted_vllm//media/public/models/huggingface/Qwen/Qwen2.5-7B-Instruct
    api_key: EMPTY
    api_base: http://localhost:8005/v1
    max_parallel_requests: 120
    max_retries: 3
    timeout: 60